name = "catppuccin-latte"

[palette]
background = "#eff1f5" # Base
text = "#4c4f69" # Text
action = "#dc8a78" # Rosewater
accent = "#5c5f77" # Subtext1
alert = "#df8e1d" # Yellow
error = "#d20f39" # Red
info = "#1e66f5" # Blue
success = "#40a02b" # Green
