name = "catppuccin-frappe"

[palette]
background = "#303446" # Base
text = "#c6d0f5" # Text
action = "#f2d5cf" # Rosewater
accent = "#a5adce" # Subtext1
alert = "#e5c890" # Yellow
error = "#e78284" # Red
info = "#8caaee" # Blue
success = "#a6d189" # Green
